lang: en
name: Mauricio Villalobos
title: Mauricio Villalobos

# see https://ogp.me/#types
type: website
url: https://mauriciov.com
image: https://avatars1.githubusercontent.com/u/26367461?s=460&u=9b379172699b3e5ec06b4e9be9457e7c2c9f800a&v=4
description: My name is Mauricio Villalobos, member of Ignition Wolf, let's talk about digital solutions.
